name: website

services:
  test:
    working_dir: /apps/pipeline
    build:
      context: ../
      dockerfile: apps/pipeline/Dockerfile
      target: test
      args:
        USER_ID: ${USER_ID}
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/website/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/website/.env.dev
        required: true
