services:
  astro-app:
    container_name: astro-dev-server
    # image: node:lts-alpine
    restart: always
    working_dir: /apps/astro-app
    build:
      context: ../
      dockerfile: apps/astro-app/Dockerfile.dev
      target: runtime
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 4321:4321
    volumes:
      - ../apps/astro-app:/apps/astro-app
    command: npm run dev -- --host

  sql-receptionist:
    container_name: sql-receptionist-dev-server
    tty: true
    # image: gcc:latest
    working_dir: /apps/sql-receptionist
    build:
      context: ../
      dockerfile: apps/sql-receptionist/Dockerfile.dev
      target: dev
    env_file:
      - .env
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
    develop:
      watch:
        - action: sync+restart
          path: ./../apps/sql-receptionist
          target: /apps/sql-receptionist
          initial_sync: true
    ports:
      - 2523:2523
    depends_on:
      database:
        condition: service_healthy
    command: make

  # @TODO secrets for db authentication
  database:
    container_name: postgres
    image: postgres
    working_dir: /apps/postgres
    restart: always
    build:
      context: ../
      dockerfile: apps/postgres/Dockerfile.dev
      target: dev
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USERNAME}" ]
      interval: 60s
      timeout: 5s # problem with timeout < interval?
      retries: 10
    volumes:
      - postgres-db:/var/lib/postgresql/data
      # - ./../apps/postgres/data:/var/lib/postgresql/data
    shm_size: 128mb

volumes:
  postgres-db:
