services:
  astro-app:
    # image: node:lts-alpine
    working_dir: /apps/astro-app
    build:
      context: ../
      dockerfile: apps/astro-app/Dockerfile.dev
      target: runtime
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - 4321:4321
    volumes:
      - ../apps/astro-app:/apps/astro-app
    command: npm run dev -- --host

  sql-receptionist:
    # image: gcc:latest
    working_dir: /apps/sql-receptionist
    build:
      context: ../
      dockerfile: apps/sql-receptionist/Dockerfile.dev
      target: dev
    ports:
      - 2523:2523