FROM node:lts AS runtime

WORKDIR /apps/astro-app

# install packages
COPY ./apps/astro-app/package*.json ./
RUN npm install

# copy over the rest of the files (astro files & global config)
# COPY ./apps/astro-app/. ./
COPY ./config.yml ./../../

ENV HOST=0.0.0.0
ENV PORT=4321
EXPOSE 4321