FROM python:3.14.0-bookworm AS builder
WORKDIR /apps/sql-receptionist

COPY ./apps/sql-receptionist .
COPY ./config.yml /

ENV POSTGRES_PORT=5432
ENV DB_USER=postgres
ENV DB_PASSWORD=password

RUN pip install psycopg2-binary
RUN pip install --no-cache-dir PyYAML

RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    libpq-dev \
    libyaml-dev \
    wget \
    bzip2 \
    gnupg \
    # @TODO verification with gnupg
    # QoL
    gdb \
    nano
RUN wget https://github.com/akheron/jansson/releases/download/v2.14.1/jansson-2.14.1.tar.bz2 \
    && bunzip2 -c jansson-2.14.1.tar.bz2 | tar xf - \
    && cd jansson-2.14.1 \
    && ./configure \
    && make \
    && make check \
    && make install

RUN wget https://github.com/tlsa/libcyaml/archive/refs/tags/v1.4.2.tar.gz \
    && tar -xvzf v1.4.2.tar.gz \
    && cd libcyaml-1.4.2 \
    && make \
    && make install VARIANT=debug

# make sure the compiler knows where to look for the libcyaml & jansson libraries
RUN ldconfig

RUN make

EXPOSE 2523
EXPOSE 5432

CMD ["create_tables.py", "&&", "./app"]